name: SnowyRPGPlugin
version: 0.1
author: LoudbookAndSnowedSeal
main: me.loudsnow.mcplug.Main
api-version: 1.18
commands:
  booktest:
    description: Test for Book
    usage: /booktest
  banker:
    description: Get the bank (devs only)
    usage: /banker
  getwindstep:
    description: Get Windstep [REMOVE]
    usage: /getwindstep
  getmeteorslam:
    description: Get Meteor Slam
    usage: /getmeteorslam
  getshadowleap:
    description: Get Shadowleap
    usage: /getshadowleap
  getdesolation:
    description: Get Desolation
    usage: /getdesolation
  gettruedesolation:
    description: Get Awakened Desolation
    usage: /gettruedesolation
  getstarterdagger:
    description: Get basic dagger
    usage: /getstarterdagger
  getstartersword:
    description: Get basic sword
    usage: /getstartersword